[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"
  functions = "functions"

[functions]
  directory = "backend/src/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "https://automated-deployment-frontend-uc5h.vercel.app/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 